### ISSUE TITLE
help with mqtt configuration

### ISSUE THREAD

**Issue by n0is3r** [kasitoru/mjsxj02hl_application#10]
hi, 
cant add to Mosquitto broker on home assistant,how can i do manualy?
thanks

**Comment by avdeevsv91** [comment]
Try it:
```yaml
value_template: "{{ value_json['humanoid'] }}"
```
and show the contents of the topic _mjsxj02hl/alarm_

**Comment by TheBisk** [comment]
Hi avdeevsv91,
it's been a few days I haven't received any more movement alarms from MQTT. I see in the broker log that the cam is always disconnected due to timeout.

  1635977478: New client connected from 192.168.178.117 as MJSXJ02HL (p2, c1, k60, u'User'). 
  1635977568: Client MJSXJ02HL has exceeded timeout, disconnecting.

Even from mqtt explorer I don't see any alarm messages. I tried to restart the device but nothing has changed.

- platform: mqtt
   name: GiardinoIpCam Human Motion
   device_class: motion
   state_topic: "mjsxj02hl/alarm"
   value_template: "{{ value_json.humanoid }}"
   payload_on: true
   payload_off: false
   
 - platform: mqtt
   name: GiardinoIpCam Motion
   device_class: motion
   state_topic: "mjsxj02hl/alarm"
   value_template: "{{ value_json.motion }}"
   payload_on: true
   payload_off: false

Any idea on how to fix it?
Tks

**Comment by avdeevsv91** [comment]
@TheBisk, show the camera log

**Comment by TheBisk** [comment]
how to access the log file?
![image](https://user-images.githubusercontent.com/47088987/140504714-b385ab92-6bca-40f3-a940-3f4e655c3b34.png)

**Comment by avdeevsv91** [comment]
Set filepath `/mnt/mmc/log.txt`, insert sd cart and reboot you camera.

**Comment by TheBisk** [comment]
mqtt][mqtt_send]: Topic: mjsxj02hl/alarm
[mqtt][mqtt_send]: Payload: {"motion":true,"humanoid":false,"timestamp":1636115231}
[mjsxj02hl_application][signal_callback]: Function is called...
[mjsxj02hl_application][signal_callback]: local_sdk_indicator_led_option(true, false) success.
[mqtt][mqtt_free]: Function is called...
[mqtt][mqtt_free]: pthread_cancel(periodical_thread) success.
[mqtt][mqtt_send]: MQTTClient_publishMessage() error!
[mqtt][mqtt_send]: Function completed.
[alarm][alarm_state_mqtt]: mqtt_send() error!
[alarm][alarm_state_mqtt]: Function completed.
[alarm][alarm_state_timeout]: alarm_state_mqtt() error!
[mqtt][mqtt_send]: MQTTClient_publishMessage() error!
[mqtt][mqtt_send]: Function completed.
[mqtt][mqtt_periodical]: mqtt_send() error!
[mqtt][mqtt_periodical]: Function completed.
[mqtt][mqtt_message_callback]: Function completed.
[mqtt][mqtt_free]: MQTTClient_unsubscribe() error!
[mqtt][mqtt_free]: MQTTClient_disconnect() success.
[mqtt][mqtt_free]: Function completed.
[mjsxj02hl_application][signal_callback]: mqtt_free(true) error!
[rtsp][rtsp_free]: Function is called...
[rtsp][rtspserver]: Stopping the media session #2...
[mqtt][mqtt_disconnect_callback]: Function is called...
[mqtt][mqtt_disconnect_callback]: The connection to the MQTT server was lost! Wait 60 seconds...
[mqtt][mqtt_free]: Function is called...
[mqtt][mqtt_free]: pthread_cancel(periodical_thread) error!
[mqtt][mqtt_free]: MQTTClient_unsubscribe() error!
[mqtt][mqtt_free]: MQTTClient_disconnect() error!
[mqtt][mqtt_free]: Function completed.
[rtsp][rtspserver]: Stopping the media session #3...
[rtsp][rtspserver]: The RTSP server is stopped.
[rtsp][rtsp_free]: rtspserver_free() success.
[rtsp][rtsp_free]: Function completed.

**Comment by avdeevsv91** [comment]
Need a full log. Use pastebin

**Comment by TheBisk** [comment]
Here is my log, debbuging errors:
https://pastebin.com/mUf1ZNCi

I see errors for night mode and alarm, no problem for the video stream,
Thanks.

**Comment by avdeevsv91** [comment]
Set logger level to "debug" and try again

**Comment by TheBisk** [comment]
> Set logger level to "debug" and try again

Here you are --> https://pastebin.com/DuyN3RKF

I cannot understand why my binary_sensors humanoid and motion are not working anymore.

Thanks.

**Comment by avdeevsv91** [comment]
@TheBisk There are no errors in the log when sending MQTT messages. Use MQTT Explorer, subscribe to `mjsxj02hl/#` and check inbox messages.

**Comment by TheBisk** [comment]
@kasitoru Can you please show a script for getting a screenshot by the cam?

**Comment by kasitoru** [comment]
@TheBisk I don't use it, but you can get pictures just by downloading an image at this address `http://<camera_ip>/cgi-bin/get_image.cgi`
