### ISSUE TITLE
Hi3518Ev300 toolchain is down

### ISSUE THREAD

**Issue by abrahamfa** [kasitoru/mjsxj02hl_application#11]
The Hi3518Ev300  link is down and I can't find an alternate link.

Do you have any other alternative?

And a offtopic question: 

Do you have the original firmware? I have taken it from this video (https://youtu.be/1prNTrTY3Fs) but I think my camera's wifi device is broken. I was testing with your firmware but I think something happened

Thanks!

**Comment by kasitoru** [comment]
Toolchain: https://t.me/mjsxj02hl_firmware/1813
Original firmware: https://4pda.to/forum/index.php?s=&showtopic=989925&view=findpost&p=108711982
Full dump of original firmware: https://kasito.ru/proshivka-zagruzchika-ip-kamery-mjsxj02hl-s-pomoshhyu-ch341a/

**Comment by abrahamfa** [comment]
Thank you very much for your quick reply.

I will try this.

Thanks!
