### ISSUE TITLE
change url rtsp stream

### ISSUE THREAD

**Issue by suszabla** [kasitoru/mjsxj02hl_application#21]
Hello, it is possible to change url in rtsp server?
for example change:
rtsp://user:password@192.168.1.18:554/secondary
to:
rtsp://user:password@192.168.1.18:554/cam/realmonitor?channel=1&subtype=1

Or do you have idea to create url alias, like in webservers?

**Comment by kasitoru** [comment]
You can only change the channel name (Settings - RTSP server - Channel name):

`rtsp://user:password@192.168.1.18:554/custom_channel_name`
